#= require jquery
#= require jquery_ujs
#= require jquery.ui.core
#= require jquery.ui.widget
#= require jquery.ui.slider
#= require_tree .
#= require uikit/uikit
#
# Markdown editor
#= require codemirror
#= require codemirror/modes/markdown
#= require codemirror/addons/mode/overlay
#= require codemirror/modes/xml
#= require codemirror/modes/gfm
#= require marked
#= require uikit/addons/htmleditor
#= require uikit/addons/form-select
#= require uikit/addons/search
#= require uikit/addons/autocomplete
